name: Build and Upload netalyze Artifacts

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install cross
      run: cargo install cross

    - name: Update version in Cargo.toml
      run: |
        TAG_NAME=${GITHUB_REF#refs/tags/netalyze-}
        sed -i "s/^version = \".*\"/version = \"$TAG_NAME\"/g" netalyze/Cargo.toml

    - name: Run build.sh
      run: chmod +x netalyze/build.sh && netalyze/build.sh

    - name: Upload artifacts
      uses: skx/github-action-publish-binaries@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: release/netalyze_*